import { useEffect, useState } from "react";
import { saveResume, getResume } from "../api";
import jsPDF from "jspdf";

function Resume({ resumeData, setResumeData }) {

  const [downloading, setDownloading] = useState(false);

  // ============================================
  // LOAD EXISTING RESUME
  // ============================================

  useEffect(() => {

    const token = localStorage.getItem("token");

    if (!token) {
      return;
    }

    getResume(token)
      .then((data) => {

        setResumeData({
          name: data.name || "",
          email: data.email || "",
          college: data.college || "",
          skills: data.skills || "",
        });

      })
      .catch((error) => {

        if (error.message !== "Resume not found") {
          console.error("Get resume error:", error);
        }

      });

  }, [setResumeData]);


  // ============================================
  // HANDLE INPUT
  // ============================================

  const handleChange = (e) => {

    const { name, value } = e.target;

    setResumeData((previousData) => ({
      ...previousData,
      [name]: value,
    }));

  };


  // ============================================
  // SAVE RESUME
  // ============================================

  const handleSubmit = async (e) => {

    e.preventDefault();

    const token = localStorage.getItem("token");

    if (!token) {
      alert("Please login first.");
      return;
    }

    try {

      const data = await saveResume(
        resumeData,
        token
      );

      alert(data.message);

    } catch (error) {

      console.error("Resume error:", error);

      alert(error.message);

    }

  };


  // ============================================
  // DOWNLOAD RESUME PDF
  // ============================================

  const downloadResume = () => {

    try {

      setDownloading(true);

      const pdf = new jsPDF(
        "p",
        "mm",
        "a4"
      );

      const pageWidth =
        pdf.internal.pageSize.getWidth();

      const pageHeight =
        pdf.internal.pageSize.getHeight();


      // ========================================
      // RESUME DATA
      // ========================================

      const name =
        resumeData.name || "Your Name";

      const email =
        resumeData.email || "your@email.com";

      const college =
        resumeData.college || "Your College";

      const skills =
        resumeData.skills || "Your skills";


      // ========================================
      // NAME
      // ========================================

      pdf.setFont(
        "helvetica",
        "bold"
      );

      pdf.setFontSize(24);

      pdf.text(
        name,
        pageWidth / 2,
        25,
        {
          align: "center",
        }
      );


      // ========================================
      // EMAIL
      // ========================================

      pdf.setFont(
        "helvetica",
        "normal"
      );

      pdf.setFontSize(11);

      pdf.text(
        email,
        pageWidth / 2,
        34,
        {
          align: "center",
        }
      );


      // ========================================
      // HORIZONTAL LINE
      // ========================================

      pdf.line(
        20,
        42,
        190,
        42
      );


      // ========================================
      // EDUCATION
      // ========================================

      pdf.setFont(
        "helvetica",
        "bold"
      );

      pdf.setFontSize(15);

      pdf.text(
        "Education",
        20,
        58
      );


      pdf.setFont(
        "helvetica",
        "normal"
      );

      pdf.setFontSize(11);

      pdf.text(
        college,
        20,
        68
      );


      // ========================================
      // SKILLS
      // ========================================

      pdf.setFont(
        "helvetica",
        "bold"
      );

      pdf.setFontSize(15);

      pdf.text(
        "Skills",
        20,
        88
      );


      pdf.setFont(
        "helvetica",
        "normal"
      );

      pdf.setFontSize(11);


      // Split long skills text
      const skillLines =
        pdf.splitTextToSize(
          skills,
          170
        );


      pdf.text(
        skillLines,
        20,
        98
      );


      // ========================================
      // FOOTER
      // ========================================

      pdf.setFontSize(9);

      pdf.setTextColor(
        100,
        100,
        100
      );

      pdf.text(
        "Generated by AI Interview Coach",
        pageWidth / 2,
        pageHeight - 15,
        {
          align: "center",
        }
      );


      // ========================================
      // SAVE PDF
      // ========================================

      const fileName =
        `${name.replace(/\s+/g, "_")}_Resume.pdf`;

      pdf.save(fileName);


    } catch (error) {

      console.error(
        "PDF generation error:",
        error
      );

      alert(
        "Failed to download resume."
      );

    } finally {

      setDownloading(false);

    }

  };


  // ============================================
  // UI
  // ============================================

  return (

    <section className="resume-section">

      <h2>
        📄 Resume Builder
      </h2>


      {/* ========================================
          RESUME FORM
      ======================================== */}

      <form
        onSubmit={handleSubmit}
        className="resume-form"
      >

        {/* NAME */}

        <input
          type="text"
          name="name"
          placeholder="Enter your name"
          value={resumeData.name || ""}
          onChange={handleChange}
          required
        />


        {/* EMAIL */}

        <input
          type="email"
          name="email"
          placeholder="Enter your email"
          value={resumeData.email || ""}
          onChange={handleChange}
          required
        />


        {/* COLLEGE */}

        <input
          type="text"
          name="college"
          placeholder="Enter your college"
          value={resumeData.college || ""}
          onChange={handleChange}
          required
        />


        {/* SKILLS */}

        <textarea
          name="skills"
          placeholder="Python, DSA, React, SQL..."
          value={resumeData.skills || ""}
          onChange={handleChange}
          required
        />


        {/* SAVE BUTTON */}

        <button type="submit">
          Save Resume
        </button>

      </form>


      {/* ========================================
          RESUME PREVIEW
      ======================================== */}

      <div
        id="resume-preview"
        className="resume-preview"
      >

        <h2>
          {resumeData.name || "Your Name"}
        </h2>

        <p>
          <strong>Email:</strong>{" "}
          {resumeData.email ||
            "your@email.com"}
        </p>

        <p>
          <strong>College:</strong>{" "}
          {resumeData.college ||
            "Your College"}
        </p>

        <h3>
          Skills
        </h3>

        <p>
          {resumeData.skills ||
            "Your skills"}
        </p>

      </div>


      {/* ========================================
          DOWNLOAD BUTTON
      ======================================== */}

      <button
        type="button"
        onClick={downloadResume}
        disabled={downloading}
      >

        {downloading
          ? "Generating PDF..."
          : "📥 Download Resume"}

      </button>

    </section>

  );

}

export default Resume;